django/musiclab/music/urls.py
from django.conf.urls import patterns, url

from music import views

urlpatterns = patterns('',
   # ex: /mus/
    url(r'^$', views.index, name='index'),
    # ex: /mus/5/
    url(r'^(?P<song_id>\d+)/$', views.detail, name='detail'),
    # ex: /mus/5/comments
    url(r'^(?P<id>\d+)/comments/$', views.comments_view, name='comments_view'),
    url(r'^comments_list/$', views.comments_list, name='comments_list'),
    # ex: /mus/5/vote/
    url(r'^search/$', views.search_view, name='search_view'),
    url(r'^best/$', views.best_view, name='best_view'),
    url(r'^user/$', views.user_view, name='user_view'),
    # AJAX
    url(r'^vote/$', views.vote, name='vote'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^user/edit$', views.edit_user, name='edit_user'),
)

django/musiclab/musiclab/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'musiclab.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^mus/', include('music.urls',namespace="music")),
    url(r'^admin/', include(admin.site.urls)),
)

django/musiclab/music/models.py
from django.db import models
from django.contrib.auth.models import User


class Song(models.Model):
	id = models.AutoField(primary_key=True)
	title =  models.CharField(max_length=200)
	artist =  models.CharField(max_length=200)
	album =  models.CharField(max_length=200)
	picture =  models.CharField(max_length=200, default="/static/music/img/No_Cover.gif")
	link =  models.CharField(max_length=200, default="default")
	pub_date = models.DateTimeField('date published', auto_now_add=True)
        average = models.FloatField(default=0);
        def __unicode__(self):  # Python 3: def __str__(self):
		return '%s: %s ' % (self.artist, self.title)

class Mark(models.Model):
	id = models.AutoField(primary_key=True)
	mark = models.IntegerField()
	comment = models.CharField(max_length=512)
	pub_date = models.DateTimeField('date published',  auto_now_add=True)
	song = models.ForeignKey(Song)
	user = models.ForeignKey(User)

django/musiclab/music/views.py
import json
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.db.models import Avg
from music.models import Song, Mark
from django.core.paginator import Paginator
import datetime
#Main page
def index(request):
    latest_song_list = Song.objects.all().order_by('-pub_date')[:10]
    latest_mark_list = Mark.objects.all().order_by('-pub_date')[:10]
    context = {'latest_song_list': latest_song_list,
    'latest_mark_list':latest_mark_list,'sesUser':request.user}
     
    return render(request, 'music/index.html', context)

#Song details
def detail(request, song_id):
    try:
        user = request.user
        song = Song.objects.get(pk=song_id)
        user_marks = Mark.objects.filter(user_id=user.id)
        user_mark = user_marks.filter(song_id=song.id)[:1]
    except Song.DoesNotExist:
        raise Http404
    return render(request, 'music/detail.html', {'sesUser':request.user,'song': song,'average':song.average, "user_mark":user_mark})

#Serach page
def search_view(request):
    search=request.GET["search_text"];    
    song_title_list = Song.objects.filter(Q(title__icontains=search)).order_by('pub_date')
    song_artist_list = Song.objects.filter(Q(artist__icontains=search)).order_by('pub_date')
    song_album_list = Song.objects.filter(Q(album__icontains=search)).order_by('pub_date')
    
    context={"song_title_list":song_title_list,"search":search,"song_artist_list":song_artist_list,"song_album_list":song_album_list}
    return render(request, 'music/search.html', context)

#Best list page
def best_view(request):
    song_list = Song.objects.all().order_by('-average')[:10]
    return render(request, 'music/best.html', {"best":song_list,'sesUser':request.user})

#User page
def user_view(request):    
    return render(request, 'music/user.html', {"sesUser":request.user,"mark_list":Mark.objects.filter(user_id=request.user.id).order_by('-pub_date')})

def comments_view(request,id):     
    song = Song.objects.get(pk = id)
    marks_list = Mark.objects.filter(song_id = id)
    pag = Paginator(marks_list,10)
    return render(request,'music/comments.html',{'sesUser':request.user,"song":song,"pages":pag.num_pages,"count":pag.count})

def comments_list(request):
    id = int(request.POST.get('song_id'))
    amount = int(request.POST.get('amount'))
    n_page = int(request.POST.get('page'))
    marks_list = Mark.objects.filter(song_id=id)
    pag = Paginator(marks_list, amount)
    response_data = {}
    response_data["list"]=[]
    for mark in pag.page(n_page).object_list:
        m = {
        "mark":mark.mark,
        "comment":mark.comment,
        "user_id":mark.user.id,
        "date": convertDatetimeToString(mark.pub_date),
        "username":mark.user.username
        }
        response_data["list"].append(m)
    response_data["total"] = pag.count
    response_data["pages"] = pag.num_pages
    return HttpResponse(json.dumps(response_data), content_type="application/json")

def convertDatetimeToString(o):
	DATE_FORMAT = "%Y-%m-%d" 
	TIME_FORMAT = "%H:%M:%S"

	if isinstance(o, datetime.date):
	    return o.strftime(DATE_FORMAT)
	elif isinstance(o, datetime.time):
	    return o.strftime(TIME_FORMAT)
	elif isinstance(o, datetime.datetime):
	    return o.strftime("%s %s" % (DATE_FORMAT, TIME_FORMAT))
#AJAX user-edit
def edit_user(request):
    user = User.objects.get(pk=request.user.id)
    new_fname = request.POST.get("first_name")
    new_lname = request.POST.get("last_name")
    new_email = request.POST.get("email_name")
    response_data = {}
    if new_fname is not None:
        user.first_name = new_fname       
    if new_lname is not None:
       user.last_name = new_lname
    if new_email is not None:
        try:
            test_user = User.objects.get(email=new_email);
            response_data["reuslt"] = "false"
            response_data["cause"] = "email exist"
        except:
            user.email = new_email
    user.save()
    return HttpResponse(json.dumps({"result": "OK"}), content_type="application/json")

#AJAX Rate song
def vote(request):
    p = get_object_or_404(Song, pk=int(request.POST["song_id"]))
    user = request.user
    user_marks = Mark.objects.filter(user_id=user.id)
    userMark = int(request.POST['userMark'])
    userComment = request.POST['userComment']
    newMark = Mark(mark=userMark, comment=userComment)
    response_data = {}
    try:
        user_song = user_marks.filter(song_id=p.id)[0]        
        user_song.delete()
    except:
        response_data['first']="true"
    newMark.song = p
    newMark.user = user        
    newMark.save()
    p.average = p.mark_set.aggregate(Avg('mark')).values()[0]
    p.save()
    response_data['average'] = p.average
    response_data['comment'] = newMark.comment
    response_data['username'] = user.username
    response_data['mark'] = userMark
    response_data['new_id'] = newMark.id
    return HttpResponse(json.dumps(response_data), content_type="application/json")

#AJAX-login
def login_view(request):
    password = request.POST['password']
    name = request.POST['login']
    us = authenticate(username=name, password=password)
    response_data = {}
    if us is not None:
        login(request, us)
        response_data['result'] = 'success'
        response_data['username'] = us.username
        response_data['user_id'] = us.id
    else:
        response_data['result'] = 'fail'        
    return HttpResponse(json.dumps(response_data), content_type="application/json")

#AJAX-register
def register(request):
    uEmail = request.POST['email']
    uNickname = request.POST['nickname']
    uPassword = request.POST['password']
    response_data = {}
    try:
        tstUser = User.objects.get(email=uEmail)    
        response_data['result'] = 'error'
        response_data['message'] = 'E-mail already exist!'
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    except:
        us =  User.objects.create_user(uNickname,uEmail,uPassword)        
        us.save()
        response_data['result'] = 'success'
        return HttpResponse(json.dumps(response_data), content_type="application/json")

#AJAX Logout
def logout_view(request):
    logout(request)
    response_data = {}
    response_data['result'] = 'success'
    return HttpResponse(json.dumps(response_data), content_type="application/json")

"""Three bellow not actual!"""
def user_top(request):
        return render(request, 'music/user.html', {"sesUser":request.user,"mark_list":Mark.objects.filter(user_id=request.user.id).order_by('-pub_date')})

def user_bottom(request):
    return render(request, 'music/user.html', {"sesUser":request.user,"mark_list":Mark.objects.filter(user_id=request.user.id).order_by('-pub_date')})

def user_last(request):
    return render(request, 'music/user.html', {"sesUser":request.user,"mark_list":Mark.objects.filter(user_id=request.user.id).order_by('-pub_date')})

django/musiclab/music/templates/music/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>MusicLab</title>
        {% load staticfiles %}
        {% block import%}        
        <link href="{% static 'music/css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'music/css/bootstrap-responsive.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'music/css/jquery.rating.css' %}">
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'music/ico/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'music/ico/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'music/ico/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'music/ico/apple-touch-icon-57-precomposed.png' %}">
        <link rel="shortcut icon" href="{% static 'music/ico/favicon.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
        {% endblock import %}
    </head>
    <body>
        {% block headbar%}
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="{% url 'music:index' %}">MusicLab</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li><a href="{% url 'music:index' %}">Home</a></li>
                            <li><a href="{% url 'music:best_view' %}">Top 10</a></li>
                        </ul>
                        <form class="navbar-form pull-right" id="loginForm">
                            {% csrf_token %}
                            <input class="span2" type="text" placeholder="Login" name="login" id='loginHolder'>
                            <input class="span2" type="password" placeholder="Password" name="password" >
                            <button type="button" class="btn btn-success" id="loginButton">Login</button>
                            <a href="#myModal" id="regButton" role="button" class="btn" data-toggle="modal">Register</a>
                        </form>
                        <form id="logoutForm" hidden>
                            {% csrf_token %}
                        </form>
                        <div id = "userHolder" class="navbar-form pull-right" hidden><a  href= "{% url 'music:user_view' %}" class="btn btn-primary" id="userButton"><i class="icon-user icon-white"></i> {{ sesUser.username }}</a> <button class="btn" id="logoutButton">Logout</button></div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock headbar%}
        <div class="container">
            
            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                {% block search %}
                <div id="serachHolder" style="float:right;">
                    <form class="form-search" method="GET" action="{% url 'music:search_view' %}">
                        <input type="text" class="input-large search-query" name="search_text">
                        <button type="submit" class="btn">Найти</button>
                    </form>
                </div>
                {% endblock search %}
                {% block content%}
                {% endblock content%}
            </div>

            {% block footercontent %}

            {% endblock footercontent %}

            <hr>
            <div id="hideModel" hidden="hidden">
                <div class="modal" id="modelRegister" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel">Registration</h3>
                    </div>
                    <div class="modal-body">
                        <form id="regForm" class="form-horizontal">

                            {% csrf_token %}
                            <div class="control-group" id="emailGroup"> 
                                <label class="control-label" for="email">E-mail</label>                            
                                <div class="controls">
                                    <input type="text" name="email" id="email">

                                </div>
                            </div>
                            <div class="control-group" id="nickGroup"> 
                                <label class="control-label" for="nick" >Nickname</label>
                                <div class="controls">
                                    <input type="text" name="nickname" id="nick" >
                                </div>
                            </div>
                            <div class="control-group" id="passGroup"> 
                                <label class="control-label" for="pass">Password</label>
                                <div class="controls">
                                    <input type="password" name="password" id="pass">
                                </div>
                            </div>
                            <div class="control-group" id="rePassGroup"> 
                                <label class="control-label" for="rePass">Password</label>
                                <div class="controls">
                                    <input type="password" name="rePassword" id="rePass">
                                </div>
                            </div>
                            
                            <div class="control-group" id="avaGroup" hidden>  
                                <label class="control-label" for="ava" >Link to avatar</label>
                                <div class="controls">
                                    <input type="text" name="avatar" id="ava" value='default'>
                                </div>
                            </div> 
                        </form>

                        <div id = "errorRegister" class="alert alert-error" hidden>
                            Registration Error!
                            <div id="errorMessage">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true" id="cancelButton">Cancel</button>
                        <button class="btn btn-primary" id="doRegButton">Register</button>
                    </div>
                </div>
            </div>
            <footer>
                <p>&copy; Company 2012</p>
            </footer>
     
        </div>
     
    </body>
    <!-- Dynamic element -->
    {% block element_srcipt%}
    <script>
        var LOGIN_BUTTON = "#loginButton";
        var LOGIN_FORM = "#loginForm";
        var REG_BUTTON = "#regButton";
        var REG_FORM = "#regForm";
        var CANCEL_BUTTON = "#cancelButton";
        var DO_REG_BUTTON = "#doRegButton";
        var MODAL = "#grayGround";

        var USER_HOLDER = "#userHolder";
        var LOGOUT_BUTTON = "#logoutButton";
        var LOGOUT_FORM = "#logoutForm";
        var USER_BUTTON = "#userButton";
        var login_addres = "{% url 'music:login_view' %}";
        var reg_addres = "{% url 'music:register' %}";
        var logout_addres = "{% url 'music:logout_view' %}";
        var vote_addres = "{% url 'music:vote' %}";
        var USERNAME = "{{ user.username }}";
    </script>
    {% endblock element_srcipt%}

    {% block libs_script%}
    <!-- LIBs -->
    <script src="{% static 'music/js/jquery.js' %}"></script>
    <script src="{% static 'music/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'music/js/lib/jquery.rating.pack.js' %}"></script>
    <script type="text/javascript" src="{% static 'music/js/Base.js' %}"></script>
    <script type="text/javascript" src="{% static 'music/js/lib/namespace.js' %}"></script>
    <script type="text/javascript" src="{% static 'music/js/util/Util.js' %}"></script>
    
    {% endblock libs_script%}    

    {% block page_script%}    
    {% endblock page_script%}
    
    {% block afterscript %}
    <script type="text/javascript" src="{% static 'music/js/indexApp.js' %}"></script>
    <script type="text/javascript" src="{% static 'music/js/indexApp/Controller.js' %}"></script>
    {% endblock %}
</html>

django/musiclab/music/templates/music/best.html
{% extends "music/base.html" %}
{% block content %}
{% load staticfiles %}
<!-- List of best songs -->

<div class="row">
    {% if best %}
        <h3> Top 10 Songs</h3>    
        {% for song in best %}
        <div class="span5">
            <div style="margin: 10px;">
                <img src="{{ song.picture }}" class="coverHolder" width="130"  style="float:left; margin-right: 10px;">
                {{ song }} <br>{{song.album}}<br>
                <span class="rateHolder">{{ song.average }}</span><br>
                <div style="font-size:14px;line-height:90%">
                    </div>
                <a class="btn btn-info" href="{% url 'music:detail' song.id %}">Rate!</a>
            </div>
        </div>
        {% endfor %}
            {% else %}
                <p>Sorry, all songs is lame :(</p>
        {% endif %}
</div>
{% endblock content %}

django/musiclab/music/templates/music/comments.html
{% extends "music/base.html" %}
{% block content %}
{% load staticfiles %}

<!-- List of comments -->

<h3><a href="{% url 'music:detail' song.id %}">{{ song }}</a></h3>
Total comments: {{count}} <br>
<!-- <div class="pagination" id="paginationHolder"></div> -->
<div class="row">
    <h3> All marks</h3>
   
        <div id="commentHolder" >
        </div>
    
</div>

{% endblock content %}

{% block page_script%}    
<script>
    var comments_list_adress = "{% url 'music:comments_list' %}";
    var SONG_ID = "{{ song.id }}";
    var NOT_FORBIDDEN = "{% csrf_token %}";
</script>
<script type="text/javascript" src="{% static 'music/js/commentsApp.js' %}"></script>
<script type="text/javascript" src="{% static 'music/js/commentsApp/CommentsController.js' %}"></script>
{% endblock page_script%}

django/musiclab/music/templates/music/header.html
<div id="header">
    <button> TEST HEADER</button>
</div>

django/musiclab/music/templates/music/index.html
{% extends "music/base.html" %}
{% block content %}
{% load staticfiles %}
<h2>Recently rated songs:</h2>

<div class="row">
    {% if latest_mark_list %}
    {% for mark in latest_mark_list %}
    <div class="span5">
        <div style="margin: 10px;">
            <img src="{{ mark.song.picture }}" class="coverHolder" width="140"  style="float:left; margin-right: 10px;">
            {{ mark.song }} <br>{{mark.song.album}}<br>          
            <span class="rateHolder">{{ mark.mark }}</span><br>
            <div style="font-size:14px;line-height:90%">
                <p>by {{ mark.user.username }}</p> </div>

            <a class="btn btn-info" href="{% url 'music:detail' mark.song.id %}">Rate!</a>
        </div>
    </div>
    {% endfor %}

    {% else %}
    <p>No songs are available.</p>
    {% endif %}

</div>
{% endblock content %}
{% block footercontent %}

<!-- Example row of columns -->
<div class="row">
    <h2>Recently added songs:</h2>
    {% if latest_song_list %}

    {% for song in latest_song_list %}
    <div class="span4" style="margin-top:20px; ">
        <img src="{{song.picture}}" class="coverHolder"  width="125px" style='float:left; margin-right: 5px'>
        <h5>{{song}}</h5>

        <p>{{song.album}}<br>
            <span class="rateHolder">{{ song.average}}</span>
        </p>
        <br>
        <p><a class="btn btn-info" href="/mus/{{ song.id }}/">Rate!</a></p>
    </div>
    {% endfor %}

    {% else %}
    <p>No songs are available.</p>
    {% endif %}

</div>

{% endblock footercontent %}


</html>

django/musiclab/music/templates/music/search.html
{% extends "music/base.html" %}
{% block content %}
{% load staticfiles %}
<div class="row">                    
    {% if song_title_list %}
    <h3> By title</h3>
    {% for song in song_title_list %}
    <div class="span4">
        <div >
            <img src="{{ song.picture }}" width="145px" style="float:left; margin-right: 10px;">

            <h4>{{ song }} <br></h4>

            <p><a class="btn btn-info" href="{% url 'music:detail' song.id %}">Rate!</a></p>

        </div>
    </div>
    {% endfor %}

    {% else %}

    {% endif %}
</div>


<div class="row">                    
    {% if song_artist_list %}
    <h3> By artist</h3>
    {% for song in song_artist_list %}
    <div class="span4">
        <div >
            <img src="{{ song.picture }}" width="145px" style="float:left; margin-right: 10px;">

            <h4>{{ song }} <br></h4>

            <p><a class="btn btn-info" href="{% url 'music:detail' song.id %}">Rate!</a></p>

        </div>
    </div>
    {% endfor %}

    {% else %}

    {% endif %}
</div>


<div class="row">                    
    {% if song_album_list %}
    <h3> By album</h3>
    {% for song in song_album_list %}
    <div class="span4">
        <div >
            <img src="{{ song.picture }}" width="145px" style="float:left; margin-right: 10px;">

            <h4>{{ song }} <br></h4>

            <p><a class="btn btn-info" href="{% url 'music:detail' song.id %}">Rate!</a></p>

        </div>
    </div>
    {% endfor %}

    {% else %}

    {% endif %}
</div>
{% endblock content%}

django/musiclab/music/templates/music/user.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% block search %}
{% endblock search %}
{% block content %}

<div class="row" style="background:#E6E6E6; padding: 10px;  border:1px solid #B2B2B2;">
    <h2>Profile  {{ user.username }}</h2>    
    <div>Firs name:         
        <span id="userFNameHolder">{{ user.first_name }}</span><a href="#" id="editFirstName">[edit]</a>
        <form id="firstName">
            {% csrf_token %}
            <div  id="firstNameEdior" hidden><input type="text" name="first_name" ><button class="btn" id="doneFirstName">Done</button>     
            </div>
        </form>
    </div>

    <div>Last name:
        <span id="userLNameHolder">{{ user.last_name }} </span>
        <a href="#" id="editSecondName">[edit]</a>
        <form id="lastName">
            {% csrf_token %}
            <div id="secondNameEdior" hidden><input type="text" name="last_name" >
                <button class="btn" id="doneLastName">Done</button>
            </div>
        </form>

    </div>

    <div>E-mail:
        <span id="emailHolder">{{ user.email }} </span><a href="#" id="editEmail">[edit]</a>
        <form id="email">
            {% csrf_token %}
            <div id="emailEdior" hidden><input type="text" name="email"><button  class="btn" id="doneEmail">Done</button>
            </div>
        </form>
    </div>
    
    <div>Joined: {{user.date_joined}}
        
    </div>

</div>
<div id = "userButtons" style="margin-top:20px">
    <button class="btn btn-inverse">Top 10</button> <button class="btn btn-inverse">Bottom 10</button> <button class="btn btn-inverse">Last marks</button>
</div>


<div class="row">
    <h2>Last marks:</h2>
    {% if mark_list %}
    {% for mark in mark_list %}
    <div class="span5">
        <div style="margin: 5px;">
            <img src="{{ mark.song.picture }}" class="coverHolder"  width="145px" style="float:left; margin-right: 10px;">
            {{ mark.song }} <br>{{mark.song.album}}<br>          
            <span class="rateHolder">{{ mark.mark }}</span>
            <br>
            <div style="font-size:14px;line-height:90%"><p>{{ mark.user.username }}:
                    {{ mark.comment }}</p></div>
            <a class="btn btn-info" href="{% url 'music:detail' mark.song.id %}">Rate!</a>
        </div>
    </div>
    {% endfor %}

    {% else %}
    <p>No songs are available.</p>
    {% endif %}
</div>

{% endblock content %}
{% block page_script%}
<script>
    var edit_user_adress = "{% url 'music:edit_user' %}";
</script>
<script type="text/javascript" src="{% static 'music/js/userApp.js' %}"></script>
<script type="text/javascript" src="{% static 'music/js/userApp/UserController.js' %}"></script>
{% endblock page_script%}

django/musiclab/music/templates/music/vote.html
<html>
<body>
<div id="message">
	Success! Your mark for <strong>{{song}} </strong> is {{mark}}. Thank You.<br>
	<a href="/mus/{{ song.id }}/" >Back to song</a>
</div>
</body>
</html>